#!/usr/bin/env python3
"""Scan circuits/ and regenerate circuits.js (the data the gallery reads).

Folder convention (the source of truth):
    circuits/v{v}_m{m}_s{s}_L{L}/{residual|nores}/<name>.html

Run this after adding or moving files, then commit circuits.js:
    python3 build_index.py
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
CIRCUITS_DIR = ROOT / "circuits"

# v16_m4_s2_L3  ->  groups: v, m, s, L
CONFIG_RE = re.compile(r"^v(\d+)_m(\d+)_s(\d+)_L(\d+)$")
STREAM_LABELS = {"residual": "residual", "nores": "non-residual", "res": "residual"}


def title_from(filename: str) -> str:
    return Path(filename).stem.replace("_", " ")


def main() -> None:
    entries = []
    skipped = []

    if not CIRCUITS_DIR.is_dir():
        raise SystemExit(f"No circuits/ directory at {CIRCUITS_DIR}")

    for config_dir in sorted(p for p in CIRCUITS_DIR.iterdir() if p.is_dir()):
        m = CONFIG_RE.match(config_dir.name)
        if not m:
            skipped.append(config_dir.name)
            continue
        v, mult, s, L = (int(x) for x in m.groups())

        for html in sorted(config_dir.rglob("*.html")):
            rel = html.relative_to(config_dir.parent)  # circuits/... stays out; rel from circuits/
            # stream = first subfolder under the config dir, if any
            parts = html.relative_to(config_dir).parts
            stream_key = parts[0] if len(parts) > 1 else ""
            stream = STREAM_LABELS.get(stream_key, stream_key or "unspecified")

            entries.append({
                "file": "circuits/" + str(html.relative_to(CIRCUITS_DIR)),
                "v": v, "m": mult, "s": s, "L": L,
                "stream": stream,
                "title": title_from(html.name),
            })

    # Sort: by config then stream then title for stable output
    entries.sort(key=lambda e: (e["v"], e["m"], e["s"], e["L"], e["stream"], e["title"]))

    out = ROOT / "circuits.js"
    out.write_text(
        "// AUTO-GENERATED by build_index.py — do not edit by hand.\n"
        "window.CIRCUITS = " + json.dumps(entries, indent=2) + ";\n"
    )

    print(f"Wrote {out.name}: {len(entries)} circuit(s).")
    if skipped:
        print("Skipped non-conforming folders (expected v{v}_m{m}_s{s}_L{L}):")
        for name in skipped:
            print("  -", name)


if __name__ == "__main__":
    main()
