// AUTO-GENERATED by build_index.py — do not edit by hand.
window.CIRCUITS = [
  {
    "file": "circuits/v16_m4_s2_L3/nores/sweep_circuit_nores_0.html",
    "v": 16,
    "m": 4,
    "s": 2,
    "L": 3,
    "stream": "non-residual",
    "title": "sweep circuit nores 0"
  }
];
