// AUTO-GENERATED by build_index.py — do not edit by hand.
window.CIRCUITS = [
  {
    "file": "circuits/v16_m16_s2_L3/nores/sweep_circuit_report_ex0.html",
    "v": 16,
    "m": 16,
    "s": 2,
    "L": 3,
    "stream": "non-residual",
    "title": "sweep circuit report ex0"
  }
];
